<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RecapHelper - Dashboard</title>

  <?php $this->assets->outputCss('headerCss') ?>

  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">RecapHelper</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Recap</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Bantuan
      </div>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="/bantuan/index">
          <i class="fas fa-fw fa-table"></i>
          <span>List Bantuan</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="/bantuan/create">
          <i class="fas fa-fw fa-table"></i>
          <span>Tambah Transaksi</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-0 text-gray-800">Rekap Bantuan Hingga Kini</h1><br>
          <p class="mb-4">Pilihlah salah satu kategori untuk melihat rekap data.</p>

          <button class="btn btn-primary" onclick="danaToggle()">Dana</button>
          <button class="btn btn-primary" onclick="makananToggle()">Makanan</button>
          <button class="btn btn-primary" onclick="kesehatanToggle()">Kesehatan</button>

          <!-- Begin Page Content Dana -->
          <div class="container-fluid" id="danaToggle" style="display: none;">

          <!-- Page Heading Dana -->
          <p class="mb-4">Berikut adalah pendataan dari bantuan dana yang telah diterima.</p>

          <!-- Recap Dana -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Kategori Dana</h6>
            </div>
            <div class="card-body">
            <p class="mb-4">Bantuan dalam bentuk dana/uang telah diterima dari: <b><?php echo $money_customer ?> orang</b><br>
              Bantuan dalam bentuk dana/uang telah diterima sebanyak: <b>Rp. <?php echo $money ?></b></p>
            </div>
          </div>

          <!-- DataTales Dana -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">List Transaksi</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th style="text-align: center">Nama Penggalang</th>
                      <th style="text-align: center">Jumlah Dana Bantuan</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php foreach ($danabantuans as $danabantuan) {?>
                    <tr>
                        <?php foreach ($danacustomers as $danacustomer) {
                            if($danacustomer->id == $danabantuan->id_transaksi) echo "<td>", $danacustomer->nama_penggalang, "</td>";
                        } ?>
                        <td> <?php echo "Rp ", $danabantuan->jumlah_uang; ?></td>
                    </tr>
                  <?php } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          </div>
          <!-- /.container-fluid -->

          <!-- Begin Page Content Bahan Makanan -->
          <div class="container-fluid" id="makananToggle" style="display: none;">

          <!-- Page Heading Bahan Makanan -->
          <p class="mb-4">Berikut adalah pendataan dari bantuan bahan makanan yang telah diterima.</p>

          <!-- Recap Bahan Makanan -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Kategori Bahan Makanan</h6>
            </div>
            <div class="card-body">
              Bantuan dalam bentuk bahan makanan telah diterima dari: <b><?php echo $food_customer ?> orang</b><br>
              List nama barang yang diterima, terurut dari transaksi awal:<br>
                <?php foreach($reliefitem as $item) {?>
                  <?php echo $item->nama_barang, ", ";?>
                <?php } ?>
            </div>
          </div>

          <!-- DataTales Bahan Makanan -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">List Transaksi</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th style="text-align: center">Nama Penggalang</th>
                      <th style="text-align: center">Nama Barang Bantuan</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php foreach ($makananbantuans as $makananbantuan) {?>
                    <tr>
                        <?php foreach ($makanancustomers as $makanancustomer) {
                            if($makanancustomer->id == $makananbantuan->id_transaksi) echo "<td>", $makanancustomer->nama_penggalang, "</td>";
                        } ?>
                        <td> <?php echo$makananbantuan->nama_barang; ?></td>
                    </tr>
                  <?php } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          </div>
          <!-- /.container-fluid -->

          <!-- Begin Page Content Kesehatan -->
          <div class="container-fluid" id="kesehatanToggle" style="display: none;">

          <!-- Page Heading Kesehatan -->
          <p class="mb-4">Berikut adalah pendataan dari bantuan kesehatan yang telah diterima.</p>

          <!-- Recap Kesehatan -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Kategori Kesehatan</h6>
            </div>
            <div class="card-body">
              Bantuan dalam bentuk kesehatan telah diterima dari: <b><?php echo $meds_customer ?> orang</b><br>
              List nama barang yang diterima terurut dari transaksi awal:<br>
                <?php foreach($reliefitems as $items) {?>
                  <?php echo $items->nama_barang, ", ";?>
                <?php } ?>
            </div>
          </div>

          <!-- DataTales Kesehatan -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">List Transaksi</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th style="text-align: center">Nama Penggalang</th>
                      <th style="text-align: center">Nama Barang Bantuan</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php foreach ($kesehatanbantuans as $kesehatanbantuan) {?>
                    <tr>
                        <?php foreach ($kesehatancustomers as $kesehatancustomer) {
                            if($kesehatancustomer->id == $kesehatanbantuan->id_transaksi) echo "<td>", $kesehatancustomer->nama_penggalang, "</td>";
                        } ?>
                        <td> <?php echo $kesehatanbantuan->nama_barang; ?></td>
                    </tr>
                  <?php } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          </div>
          <!-- /.container-fluid -->

        </div>

      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    function danaToggle() {
      var x = document.getElementById("danaToggle");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    function makananToggle() {
      var x = document.getElementById("makananToggle");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    function kesehatanToggle() {
      var x = document.getElementById("kesehatanToggle");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
  </script>

  <!-- Bootstrap core JavaScript-->
  <?php $this->assets->outputJs('footerJs') ?>

</body>

</html>
