<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RecapHelper - Dashboard</title>

  <?php $this->assets->outputCss('headerCss') ?>

  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">RecapHelper</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Recap</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Bantuan
      </div>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="/bantuan/index">
          <i class="fas fa-fw fa-table"></i>
          <span>List Bantuan</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item active">
        <a class="nav-link" href="/bantuan/create">
          <i class="fas fa-fw fa-table"></i>
          <span>Tambah Transaksi</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Formulir Entri Bantuan</h1>
          <p class="mb-4">Berikut adalah formulir untuk entri bantuan yang telah diterima.</p>
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Formulir</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body"> 
                  <form action="/bantuan/store" method="post">
                        <div class="form-group"><label for="nama">Nama penggalang bantuan</label>
                        <input name="nama" class="form-control" id="nama" placeholder=""></div>
                        <div class="list-barang">
                          <h6 class="m-0 font-weight-bold">List Bantuan</h6>
                          <div class="form-group">
                              <label for="kat_bantuan">Kategori bantuan</label>
                              <select name="kat_bantuan[]" class="form-control" id="kat_bantuan">
                                  <option>Dana</option>
                                  <option>Bahan makanan</option>
                                  <option>Kesehatan</option>
                              </select>
                          </div>
                          <div class="form-group">
                            <label for="jum_dana">Jumlah dana</label>
                            <input name="jum_dana[]" class="form-control" id="jum_dana" placeholder="">
                          </div>
                          <div class="form-group">
                            <label for="barang">Nama barang bantuan</label>
                            <input name="barang[]" class="form-control" id="exampleFormControlInput1" placeholder="">
                          </div>
                        </div>
                        <button type="button" onclick="dupe()" class="btn btn-primary">Tambah Bantuan</button>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>
                </div>
              </div>
          </div>
          <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <?php $this->assets->outputJs('footerJs') ?>
  <script>
    function dupe($this){
      $('.list-barang:last').clone().insertAfter('.list-barang:last');
    }
  </script>

</body>

</html>
